import Head from "next/head";
import Navbar from "../src/components/Navbar";
import "../styles/globals.css";

import type { AppProps } from "next/app";
export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Sirawit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Navbar />
      <Component {...pageProps} />
    </>
  );
}
